### ISSUE TITLE
Help with setting up mooatoon materials for a vroid material

### ISSUE THREAD

**Issue by saravanan290702** [JasonMa0012/MooaToon#11]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/a30f5c1c-56a9-43e2-a8ba-2b1ca5c0f989)

Hello so i want to use the mooatoon but i am unable to setup the materials properly..
this is supposed to be the eyes and its double sided. but using the default M_Toon i am unable to set it up.
what do i do to get to work.
thank you for ure help with this in advance

**Comment by JasonMa0012** [comment]
You need to put the Base Color Map into the Shadow Color Map at the same time.

**Comment by saravanan290702** [comment]
ah yes but its still not double sided 
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/21af4050-a546-451a-80d0-9a6ef97827c1)
this is mooaMat
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/c034fb48-c388-4362-b4cb-f939cc7585cb)
this is the mat u get from vroid as u can see the inbetween the eyes are transparent

**Comment by JasonMa0012** [comment]
https://images.app.goo.gl/JLk6zJJCnoPpnxp5A

**Comment by saravanan290702** [comment]
ah it still doesnt work, i dont know what i am doing wrong
below one is mooa toons material
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/f9cddc8e-65f1-40c0-899a-584ae7677997)
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/66deb520-285c-405a-aa09-a97a9b834d00)

Below one is vroid studio material
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/5dddd4f6-fa53-4049-9915-644e0201ed11)
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/a5361024-6d04-47af-8448-8d3f90ff8bfd)

**Comment by saravanan290702** [comment]
I am unable to make the black parts of the material go transperant
vroid mat:
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/c9bf197d-78d0-4198-9ee7-7db5d55d7674)

mooa mat:
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/c204f2e1-bc30-4d71-bd89-a6cbf1fd1230)

**Comment by JasonMa0012** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/39983625/432d4281-bd30-4a78-9ea8-05ab1e3a070c)

**Comment by saravanan290702** [comment]
Hey jason, I hope i am not bothering you but i have tried my best but i was unable to completely change the shader used by an vroid model. I would like your help in using the Mooa Toons Materials on a model imported made in vroid studio. Could you please try recreating the material instance to make the character material. Please and Thank you

**Comment by JasonMa0012** [comment]
I will try to integrate VRM4U in the next few days

**Comment by saravanan290702** [comment]
Thank you for your assistance.

**Comment by JasonMa0012** [comment]
5.3 has integrated VRM4U into the engine plugin. After the update, please delete your own installed VRM4U, and then you can directly import .vrm and generate MooaToon materials.

**Comment by saravanan290702** [comment]
WOW ty so much xD finally i can move on to learn more. When will the precompiled version for 5.4 be out for download? i would like to test some more new features out before getting the source compiled version of mooatoons

**Comment by JasonMa0012** [comment]
5.4 will undergo large-scale modifications. At present, the main functions have been completed, but there are still many details that need to be fixed. You can download the 5.4 source code version to experience it.

**Comment by saravanan290702** [comment]
ooh will wait then, in the meantime i go master the current mooatoons and animations ty for the help.

**Comment by saravanan290702** [comment]
oh also one more doubt regarding environment related materials like foilage material and landscape materials. is there any special setup for them since they are 2 sided as well. or do i juse follow how its showed in the documentation?

**Comment by JasonMa0012** [comment]
You just need to enable Two Sided in Material

**Comment by saravanan290702** [comment]
ah hello again so i had been using mooa for few days with the vroid model I guess there is very little you can do to make it look better, or i am just bad at this. i had followed most things from your documentation but some required to export out and re import. well i couldn't change the way the character looked, the shaded look i mean. 

If there is anything else that could be done, i would like to tell me on how the shaded look can be improved further just with the model imported from vrm to ue
Thank you

**Comment by JasonMa0012** [comment]
If you can't modify the VRM, then all you can do is make the character look the same as it does in VRoid Studio.
you can:
- Disable Toon Selfshadow
- Adjust shadow color by texture
- Enable hair shadow on face
- Enable outline and adjust outline color

Basically, there are only the above basic effects in VRoid Studio, which are limited by the number of triangles and texture resolution of the VRM character. It is difficult to achieve cinematic quality unless you have complete control over the character model.

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/c2c8969e-8a86-4c51-b8b8-390d187cbfb7)
is that the "Disable Toon SelfShadow"?

**Comment by JasonMa0012** [comment]
yes
