### ISSUE TITLE
240819 v544预编译版的潜在的插件的兼容性问题和其他若干建议

### ISSUE THREAD

**Issue by jpysina** [JasonMa0012/MooaToon#15]
如题，在使用最新预编译版本（v544@240819）时，发现插件兼容性问题

我一开始打算将全部工作流移入mooatoon editor中，本计划先进行风格化地编，当使用地编工具同步插件（地编工具为独立exe，使用plugin bridge与编辑器数据互通，地编工具介绍见下文链接）场景导入地形时，安装插件并勾选后重启激活过程中发生如下图报错：
![image](https://github.com/user-attachments/assets/32f9833e-efad-42bc-940f-35d5aa336254)
报错框显示插件版本不符或丢失插件，然后编辑器程序退出，删除该插件后编辑器能够进入GUI界面。对此，我尝试了重装和自编译(编译目标版本也是v543，和官方版本号一致)，无法启动的问题依旧复现。
插件是直接从epic的官方v543版本plugin中移过来的（插件文件夹直接复制到MT的 `/Engine/Plugins` 后，在插件选项卡勾选启用），官方版引擎未见报错，可直接激活该插件,尝试官方编辑器软链接到mt编辑器的插件文件夹仍无效。
在官方543编辑器中激活正常使用的插件如下图所示：
![image](https://github.com/user-attachments/assets/84d82dc6-2728-465f-8431-10cced3e72c4)

这是否是一个可修复的潜在bug？还是魔改引擎导致版本信息验证机制错位？还是自编译UE本身的机制缺陷无法修复，需要各位内容创作者先在官方编辑器完成场景后再迁移到mooatoon pj中？

个人推论猜测：除了这个插件外，可能还有其它的一些插件有同样的问题

大佬,抽空研究一下?

地编工具：[gaea 2.0,地编工具本体的官方链接](https://quadspinner.com/Download)

地编官方插件doc：https://eadocs.quadspinner.com/gaea-unreal-tools

插件已压缩打包作为本issue附件，安装直接复制到 `/Engine/Plugins` 

![image](https://github.com/user-attachments/assets/ffd3e4ef-3953-4c1d-81d2-b8fe5ca32d27)

[不兼容插件的压缩包链接在此 => GaeaUnrealTools.zip](https://github.com/user-attachments/files/16663948/GaeaUnrealTools.zip)

**Comment by JasonMa0012** [comment]
由于你使用的是二进制插件, 其是为官方版本UE编译的, 所以需要尝试修改BuildID以跳过兼容性检查, 请参考: https://support.foundry.com/hc/en-us/articles/4410634179858-Q100635-Instructions-for-building-a-custom-Nuke-Server-plug-in-for-Unreal-Engine



注意: 虽然跳过兼容性检查可以让你使用二进制插件, 但如果插件引用的模块被MooaToon修改过, 那么可能会导致崩溃.

**Comment by jpysina** [comment]
> 由于你使用的是二进制插件, 其是为官方版本UE编译的, 所以需要尝试修改BuildID以跳过兼容性检查, 请参考: https://support.foundry.com/hc/en-us/articles/4410634179858-Q100635-Instructions-for-building-a-custom-Nuke-Server-plug-in-for-Unreal-Engine
> 
> 注意: 虽然跳过兼容性检查可以让你使用二进制插件, 但如果插件引用的模块被MooaToon修改过, 那么可能会导致崩溃.

好的收到。一会儿打完黑神话去研究一下。
**除此之外，我建议**：

- 在文档FAQ中加入这个issue案例（《为什么我的插件在mt中不能激活？》），也是给后来者踩个坑。
-  **远期wip中**建议加入GUI启动器（[fluentui](https://github.com/lepoco/wpfui)）实现一站式管理，尽管命令行使用无大碍（下载预编译和自编译脚本、维护工具、插件管理、更新重载etc.）。启动器参见案例：著名stable diffusion启动器(如图)![image](https://github.com/user-attachments/assets/9128c8a6-fc5c-45c0-92d6-2b4dc1a16aa0)
- 增加预编译国内镜像archive，可以是gitcode这种github-like platform，可以是各类网盘。预编译下载使用2.5bat脚本改GitHub fastip仍然有一定几率999ms（国内有些网络环境仍然不行，天杀的救不了移不动ipv6和広·電，昨天的新版就是我wireguard挂到外省下载转发回来才成功的）
- 增加同版本号（假设：2408版本的5.4.4和2409版本的5.4.4）和跨版本（5.3 -> 5.4）预编译小版本的Δ包，实现增量更新，减少下载量

**Comment by JasonMa0012** [comment]
- 文档近期会更新
- 启动器主要面向小白和美术用户, 但实际上有能力深度使用MooaToon的用户或团队并不需要启动器, 若以后付费用户数量显著增加或者出圈了会考虑外包出去
- 同理, 下载相关优化暂时不考虑, MooaToon的目标用户应该都会用梯子
