### ISSUE TITLE
Error while running _4_0_Build_And_Run_MooaToon.bat

### ISSUE THREAD

**Issue by saravanan290702** [JasonMa0012/MooaToon#5]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/ab6de0a4-7980-490e-b8e5-7854ab214c66)

https://mooatoon.com/en/docs/GettingStarted/BuildEnginefromSourceCode
Started following from Download Zip manually

**Comment by JasonMa0012** [comment]
1. update .Net Framework (https://dotnet.microsoft.com/en-us/download/dotnet-framework)
2. restart
3. rerun _4_0_Build_And_Run_MooaToon

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/492cd5a3-5b60-47eb-96cd-cdc0c158163e)

i had have a .net framework of 4.8.1 installed already

**Comment by JasonMa0012** [comment]
Why don't you use bat tools to install?

**Comment by saravanan290702** [comment]
i had used the .bat files intially following 
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/f0c1674e-ac73-4b4c-821b-27eb8a02295a)
these steps but at one point an error similar to this had occured
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/4a15d767-5d54-423b-bb4d-bc08154ac2d7)
so i followed the second method by installing zips.

**Comment by saravanan290702** [comment]
i will re try the whole process again and see if it works

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/59c48a01-3a31-4f32-8d36-a3d2090f78b7)
even after retrying and using a proxy i got this error

**Comment by JasonMa0012** [comment]
Please try to change the proxy node, or change the network environment, such as 4/5G mobile traffic.

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/30fabccd-8f97-4e11-bc3d-ff562dadc9d6)
well the new error

**Comment by JasonMa0012** [comment]
You can try to follow the official tutorial: https://docs.unrealengine.com/5.2/en-US/building-unreal-engine-from-source/
But are you sure you have to use the source version of the engine and not the precompiled version?

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/5c84c557-e8b7-4e3b-807e-cff72142eb16)
ah i followed every step from 
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/98a874dc-889e-4d48-a3d5-7d5ab1c56b3b)
im unable to build 
i even tried the link u gave me still the same error wen tryng to run GenerateProjectFiles.bat
can u please help me

**Comment by JasonMa0012** [comment]
After the latest win11 virtual machine test, after using this tool to repair the runtime library, there is no abnormality in the source code version and the precompiled version:
https://drive.google.com/file/d/1DR80HhJu5iZ15RA71AO757_UgzG-_qig/view

**Comment by saravanan290702** [comment]
I currently use win 10. is that still fine then

**Comment by JasonMa0012** [comment]
yes

**Comment by saravanan290702** [comment]
2 questions now:
1. my antivirus detected DirectX Repair to be a trojon.gen.9 virus most of the time it does say that so wanted to confirm it.
2.  I already have a downloaded source code of the mooatoon it gives error at _4_0_Build_And_Run_MooaToon.bat do i run the DirectX Repair.exe file then run the bat file or do you want me to completely delete it and download again

**Comment by JasonMa0012** [comment]
1. The software has a history of many years, and I have tested it on win11 without any problems.
2. run the DirectX Repair.exe file then run the bat file

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/1c6d14f7-f73b-47ce-9af0-02226aabeb48)

is that error? 
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/4157fa59-3a60-416a-8fa3-e28cccf076cd)
i do have it installed tho 
once it closes it says there is no error

**Comment by JasonMa0012** [comment]
That's right, because usually windows has the latest version installed

**Comment by saravanan290702** [comment]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/91ce0035-d068-4e5b-b814-4b453c92fa2e)

still getting this error. I will install from scratch again.

**Comment by JasonMa0012** [comment]
There seems to be a problem with your system. You can try installing it on another computer or virtual machine

**Comment by JasonMa0012** [comment]
What is the result of you running _2_3_Setup_Unreal_Engine? Maybe some dependent files are not downloaded completely

**Comment by saravanan290702** [comment]
it runs without any problems
