### ISSUE TITLE
The precompiled version has too many corrupted files

### ISSUE THREAD

**Issue by saravanan290702** [JasonMa0012/MooaToon#6]
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/17ddb186-309e-42f1-a0b7-fed4622f4a97)
i have tried both the method in https://mooatoon.com/en/docs/GettingStarted/ and manually downloading the git files but there is too many broken/corrupted files due to which we cant open the unreal editor after the extraction process is completed

**Comment by JasonMa0012** [comment]
Try enabling the long path:
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by saravanan290702** [comment]
Im sorry but i dont think it works. I will look into any problem with my local environment, in the meantime i would like to request you to check the files that have been uploaded by installing them on a different pc or laptop just to confirm the problem if possible

**Comment by saravanan290702** [comment]
Im sorry but i dont think it works. I will look into any problem with my local environment, in the meantime i would like to request you to check the files that have been uploaded by installing them on a differnt pc or laptop just to confirm the problem if possible.

**Comment by JasonMa0012** [comment]
It has been verified many times that there is no problem, please run `_3_5_Update_InstallTool.bat` and reinstall

**Comment by saravanan290702** [comment]
the files have been complies but now it crashes it wont start up

**Comment by JasonMa0012** [comment]
How did the crash happen?

**Comment by saravanan290702** [comment]
![HighresScreenshot00000](https://github.com/JasonMa0012/MooaToon/assets/76428931/4a064ca6-f859-48c5-acfc-4de76151c3f8)

I think am closing this issue here. 
completed installing the precompiled version yet to check if i can make a blank project and get the toon shader to work.

for those who will face the same issue, make sure u _3_5_Update_InstallTool.bat do this first then proceed with the next steps given in the docs.

ty for helping me to get this to work.
