### ISSUE TITLE
2_3_Setup_Unreal_Engine runs without any problem while the _4_0_Build_And_Run_MooaToon.bat still gives error.

### ISSUE THREAD

**Issue by saravanan290702** [JasonMa0012/MooaToon#7]
Sorry but this is the contination of the previous thread i think i didnt complete my sentence.
wen i run _4_0_Build_And_Run_MooaToon.bat
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/57cd17ed-24e9-4478-ab6e-cdc497e28cf8)
i get this error still

**Comment by saravanan290702** [comment]
Im sorry for the inconvenience, currently i am trying on a differnt pc i will let u know if it works. can i change the repo its currently set to 5.2 i think is it possible to change it to 5.1

**Comment by JasonMa0012** [comment]
1. run _3_5_Update_InstallTool
2. open _2_5_Settings in a text editor and change all 5.2 to 5.1

**Comment by saravanan290702** [comment]
ah is it possible for u to zip the complied version and send.

**Comment by JasonMa0012** [comment]
Please update the installation tool, now you can download the corresponding precompiled version according to the version set in _2_5_Settings.bat

**Comment by JasonMa0012** [comment]
It is recommended that you test 5.2 without problems before installing 5.1

**Comment by saravanan290702** [comment]
I do have the precompiled version downloaded but this is said in docs "The disadvantage of the precompiled version is that it cannot package C++ games, does not contain debugging information, and needs to re-download the entire package every time a small update is made." 

I have to use C++ for my idea so i am trying to install the source code.

I am trying still to get it to work.

**Comment by saravanan290702** [comment]
ok i think i found where its going wrong
its this GenerateProjectFiles.bat wen i run this i get the error
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/3a858f69-0a71-45f6-8696-d234048ef83d)
it says RunUBT error: and GenerateProjectfilesError:
any help.

**Comment by JasonMa0012** [comment]
yes, have you tested compiling Epic's official version of UE? I guess there will be errors

**Comment by saravanan290702** [comment]
well i tried to download the repo manually and do the steps in the unreal engine docs on how to compile i ended up getting this error while building the soln
Severity    Code    Description    Project    File    Line    Suppression State
Error    MSB3073    The command "....\Build\BatchFiles\Build.bat -Target="UnrealEditor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.    UE5    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets    44

**Comment by JasonMa0012** [comment]
I haven't encountered this error, maybe you can google, such as
https://forums.unrealengine.com/t/build-bat-fails-exited-with-code-6/237526

**Comment by saravanan290702** [comment]
It complied but now i get this error after compliing it doesnt startup
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/b235e4b7-d898-405c-96e0-4635727f0761)

**Comment by JasonMa0012** [comment]
Please make sure that the UE official source code version compiles and runs without problems

**Comment by saravanan290702** [comment]
Closing this issue now.
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/7e9b240c-c830-4c8d-a569-57a40422dd0b)
I used followed these 2 steps and now i am able to compile successfully

**Comment by saravanan290702** [comment]
Closing this issue now.
![image](https://github.com/JasonMa0012/MooaToon/assets/76428931/7e9b240c-c830-4c8d-a569-57a40422dd0b)
I used followed these 2 steps and now i am able to complie successfully
