### ISSUE TITLE
MooaToon-Engine-Precompiled 2021.01.06 issues

### ISSUE THREAD

**Issue by AlbedoDz** [JasonMa0012/MooaToon#8]
![Untitled](https://github.com/JasonMa0012/MooaToon/assets/128199253/e587bf6b-0d27-456c-95b0-4099fd10cb71)

Hello Jason Ma. Thank you for your contribution to the community. I'd like to inquire about the 2021.01.06 build; it seems to have some issues. Your Blueprints and plugins are not running correctly

**Comment by JasonMa0012** [comment]
Fixed in 5.3-2024.01.14
